// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/host": {
            "get": {
                "description": "获取所有主机",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "获取所有主机",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payload.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Host"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新主机",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "更新主机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机 ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主机名称",
                        "name": "hostname",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "user",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "地址",
                        "name": "addr",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "SSH端口",
                        "name": "port",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "SSH密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "组ID",
                        "name": "group",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "密钥ID",
                        "name": "private_key_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "标签ID列表序列化字符串",
                        "name": "tags",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "VNC端口",
                        "name": "vnc_port",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payload.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Host"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建主机",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "创建主机",
                "parameters": [
                    {
                        "type": "string",
                        "description": "主机名称",
                        "name": "hostname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "user",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "地址",
                        "name": "addr",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "SSH端口",
                        "name": "port",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "SSH密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "组ID",
                        "name": "group",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "密钥ID",
                        "name": "private_key_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "标签ID列表序列化字符串",
                        "name": "tags",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "VNC端口",
                        "name": "vnc_port",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payload.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Host"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    }
                }
            }
        },
        "/host/{id}": {
            "get": {
                "description": "获取单个主机",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "获取单个主机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/payload.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Host"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除主机",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host"
                ],
                "summary": "删除主机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主机 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/payload.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Group": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mode": {
                    "description": "0.主机模式, 1.其他匹配模式主机不生效",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "string"
                }
            }
        },
        "models.Host": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "group": {
                    "$ref": "#/definitions/models.Group"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "private_key_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "tunnels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tunnel"
                    }
                },
                "user": {
                    "type": "string"
                },
                "vnc_port": {
                    "type": "integer"
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Tunnel": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "payload.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "type": {
                    "description": "data msg error",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
